#!/bin/sh
# https://www.isticktoit.net/?p=1383
# Licensed on MIT

ecm_enabled() {
	return 0
}

ecm_run() {
    mount -t configfs configfs /sys/kernel/config

	cd /sys/kernel/config/usb_gadget/
	mkdir -p g
	cd g
	echo 0x1d6b > idVendor # Linux Foundation
	echo 0x0104 > idProduct # Multifunction Composite Gadget
	echo 0x0100 > bcdDevice # v1.0.0
	echo 0x0200 > bcdUSB # USB2
	mkdir -p strings/0x409
	echo "0123456789" > strings/0x409/serialnumber
	echo "Allwinner Inc." > strings/0x409/manufacturer
	echo "Mangopi-MQ" > strings/0x409/product
	mkdir -p configs/c.1/strings/0x409
	echo "Config 1: ECM network" > configs/c.1/strings/0x409/configuration
	echo 250 > configs/c.1/MaxPower

	# Add functions here	
	mkdir -p functions/ecm.usb0
	ln -s functions/ecm.usb0 configs/c.1/
	# End functions

	ls /sys/class/udc > UDC

    # Configure interface
    sleep 2
    ifconfig usb0 192.168.20.2 netmask 255.255.255.0 up
}
